### ISSUE TITLE
Maybe a quick start guide on how to use binder in readme

### ISSUE THREAD

**Issue by casouri** [rnkn/binder#2]
Having read through the readme I'm still not sure how to use Binder. I enabled `binder-mode` and tried `binder-toggle-sidebar` and `binder-add-file`, both result in an error. Maybe you can demonstrate (in words) a typical workflow from scratch?

**Comment by rnkn** [comment]
Thanks for the report. Are you getting the following error?
~~~
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
~~~
This at least should be fixed in 3c8bd24 but there are still some problems when there's no existing `.binder.el` file. I'm still committing/pushing a bunch of fixes, but you should be able to force your way through for the time being by calling `M-: (binder-init-binder-file)`.

I've pushed a more comprehensive tutorial as interactive binder project as part of the repo.

**Comment by casouri** [comment]
Sounds good :-)

**Comment by rnkn** [comment]
There's now a tutorial subdirectory in the repo. If this seems enough to get you started you can close this issue.

**Comment by casouri** [comment]
Very cool! One nitpick: I was instructed to hit `C-c ]` to open the sidebar, and the next instruction is `C-c [`. So I hit it while in the sidebar buffer. That pops another window to show the new file. Maybe disable `C-c [` in the sidebar or do something intelligent?

**Comment by rnkn** [comment]
`C-c ]` should go to next file.

**Comment by casouri** [comment]
Sorry I mean `C-c ;` jumps to the sidebar and the tutorial said hit `C-c ]`. I did so and another window showing the next file pops up. Whereas hitting `C-c ]` in the text buffer takes my directly to the next file.

**Comment by rnkn** [comment]
But here it says type `q` to quit the sidebar: https://github.com/rnkn/binder/blob/master/tutorial/start-here.txt#L7

Or do you mean in another file?
